# MySQLDatabase
spring.datasource.url=jdbc:mysql://localhost:3306/cinema_db
spring.datasource.username=root
spring.datasource.password=Charik@24
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA/Hibernate
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true

# MailSetup - Mailtrap Configuration for testing email sending functionality
spring.mail.host=sandbox.smtp.mailtrap.io
spring.mail.port=2525
spring.mail.username=e206bfe95ac706
spring.mail.password=19154b855c5f89

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# AI Recommendation System Configuration: Google Gemini API
#gemini.apiKey=AIzaSyC07XSKl1qk0Wjh84MmxSE6CYmaWA92AXU

# Server Configuration
server.port=8080
