package theatreBooking;

import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;

import java.net.URI;
import java.net.http.HttpClient;
import java.net.http.HttpRequest;
import java.net.http.HttpResponse;
import java.time.Duration;

@RestController
@RequestMapping("/api/recommendations")
@CrossOrigin(origins = "http://localhost:4200")
public class RecommendationController {

    private final RecommendationService recommendationService;
    private final AppProperties AppProperties;

    public RecommendationController(RecommendationService recommendationService, AppProperties appProperties) {
        this.recommendationService = recommendationService;
        this.AppProperties = appProperties;
    }

    /**
     * GET /api/recommendations/{userId}: Returns a list of recommended movies for
     * the given customer, generated by the AI recommendation service.
     */
    @GetMapping("/{userId}")
    public ResponseEntity<?> getRecommendations(@PathVariable Long userId) {
        try {
            return ResponseEntity.ok(recommendationService.getRecommendations(userId));
        } catch (RuntimeException e) {
            return ResponseEntity.badRequest().body(e.getMessage());
        }
    }

    @GetMapping("/test")
    public ResponseEntity<String> testKey() {
        return ResponseEntity.ok("Key starts with: " +
                AppProperties.getApiKey().substring(0, 8));
    }

    @GetMapping("/ping")
    public ResponseEntity<String> pingGemini() {
        String key = AppProperties.getApiKey();
        if ("NOT_CONFIGURED".equals(key) || key.isBlank()) {
            return ResponseEntity.badRequest().body("API key not configured");
        }
        String url = "https://generativelanguage.googleapis.com/v1beta/models/"
                + "gemini-2.5-flash:generateContent?key=" + key;
        String body = "{\"contents\":[{\"parts\":[{\"text\":\"Reply with only the number 42\"}]}],"
                + "\"generationConfig\":{\"maxOutputTokens\":10,\"temperature\":0.0}}";
        try {
            HttpRequest req = HttpRequest.newBuilder()
                    .uri(URI.create(url))
                    .header("Content-Type", "application/json")
                    .timeout(Duration.ofSeconds(20))
                    .POST(HttpRequest.BodyPublishers.ofString(body))
                    .build();
            HttpResponse<String> resp = HttpClient.newBuilder()
                    .connectTimeout(Duration.ofSeconds(15))
                    .build().send(req, HttpResponse.BodyHandlers.ofString());
            return ResponseEntity.ok("HTTP " + resp.statusCode() + "\n\n" + resp.body());
        } catch (Exception e) {
            return ResponseEntity.internalServerError()
                    .body("Error: " + e.getClass().getSimpleName() + " — " + e.getMessage());
        }
    }
}